if(EXISTS "/home/lijianxian/workshop/initLTQMDD/release/test/qfr_test[1]_tests.cmake")
  include("/home/lijianxian/workshop/initLTQMDD/release/test/qfr_test[1]_tests.cmake")
else()
  add_test(qfr_test_NOT_BUILT qfr_test_NOT_BUILT)
endif()
